/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import interfaces.OnBusinessObjectSaved;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import librarievirtuala.Autor;
import librarievirtuala.Carte;
import librarievirtuala.Editura;
import repositories.CartiMemoryRepository;
import servicies.CartiService;
import servicies.CartiServiceImpl;

/**
 *
 * @author Andrei
 */
public class FrmAddEditCarte extends javax.swing.JDialog {

    /**
     * Creates new form FrmAddEditCarte
     */

    public FrmAddEditCarte(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JTextArea getTxtDescriere() {
        return txtDescriere;
    }

    public JTextField getTxtIsbn() {
        return txtIsbn;
    }

    public JTextField getTxtNume() {
        return txtNume;
    }

    public JSpinner getSpnPret() {
        return spnPret;
    }

    public JList<Autor> getLstAutori() {
        return lstAutori;
    }

    public JButton getBtnSave() {
        return btnSave;
    }
    

    public JComboBox<Editura> getCmbEdituri() {
        return cmbEdituri;
    }
    

    public FrmAddEditCarte(Carte carteSelectata, JDialog parent, boolean modal) {
        this(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edituraComboBoxRenderer1 = new renderers.EdituraComboBoxRenderer();
        autorListRenderer1 = new renderers.AutorListRenderer();
        lblIsbn = new javax.swing.JLabel();
        lblNume = new javax.swing.JLabel();
        lblPret = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        txtNume = new javax.swing.JTextField();
        lblDescriere = new javax.swing.JLabel();
        lblAutori = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescriere = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAutori = new javax.swing.JList<>();
        btnSave = new javax.swing.JButton();
        cmbEdituri = new javax.swing.JComboBox<>();
        spnPret = new javax.swing.JSpinner();

        edituraComboBoxRenderer1.setText("edituraComboBoxRenderer1");

        autorListRenderer1.setText("autorListRenderer1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIsbn.setText("Isbn:");

        lblNume.setText("Nume:");

        lblPret.setText("Pret:");

        jLabel4.setText("Editura:");

        lblDescriere.setText("Descriere:");

        lblAutori.setText("Autor/Autori:");

        txtDescriere.setColumns(20);
        txtDescriere.setRows(5);
        jScrollPane1.setViewportView(txtDescriere);

        lstAutori.setCellRenderer(autorListRenderer1);
        jScrollPane2.setViewportView(lstAutori);

        btnSave.setText("Salvare");

        cmbEdituri.setRenderer(edituraComboBoxRenderer1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAutori)
                                .addComponent(lblIsbn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblNume, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPret, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblDescriere))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(txtIsbn)
                            .addComponent(txtNume)
                            .addComponent(jScrollPane2)
                            .addComponent(cmbEdituri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNume)
                    .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPret)
                    .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbEdituri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutori)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescriere, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private renderers.AutorListRenderer autorListRenderer1;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Editura> cmbEdituri;
    private renderers.EdituraComboBoxRenderer edituraComboBoxRenderer1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAutori;
    private javax.swing.JLabel lblDescriere;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblPret;
    private javax.swing.JList<Autor> lstAutori;
    private javax.swing.JSpinner spnPret;
    private javax.swing.JTextArea txtDescriere;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNume;
    // End of variables declaration//GEN-END:variables

}
