/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import interfaces.OnBusinessObjectSaved;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import librarievirtuala.Raft;
import repositories.RafturiMEmoryRepository;
import servicies.RafturiService;
import servicies.RafturiServiceImpl;

/**
 *
 * @author Andrei
 */
public class FrmAddEditRaft extends javax.swing.JDialog {



    /**
     * Creates new form FrmAddEditRaft
     */
    public FrmAddEditRaft(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        lblNume = new javax.swing.JLabel();
        lblNrLinii = new javax.swing.JLabel();
        lblNrColoane = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        spnNrLinii = new javax.swing.JSpinner();
        spnNrColoane = new javax.swing.JSpinner();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNume.setText("Nume:");

        lblNrLinii.setText("Numar maxim de lini:");

        lblNrColoane.setText("Numar maxim de colane:");

        btnSave.setText("Salvare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNrColoane)
                            .addComponent(lblNume, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNrLinii, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNume)
                            .addComponent(spnNrColoane, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(spnNrLinii)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrLinii)
                    .addComponent(spnNrLinii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrColoane)
                    .addComponent(spnNrColoane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSave))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JSpinner getSpnNrLinii() {
        return spnNrLinii;
    }

    public JSpinner getSpnNrColoane() {
        return spnNrColoane;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    /**
     * @param args the command line arguments
     */

    public JTextField getTxtNume() {
        return txtNume;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lblNrColoane;
    private javax.swing.JLabel lblNrLinii;
    private javax.swing.JLabel lblNume;
    private javax.swing.JSpinner spnNrColoane;
    private javax.swing.JSpinner spnNrLinii;
    private javax.swing.JTextField txtNume;
    // End of variables declaration//GEN-END:variables
}
