/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import interfaces.OnBusinessObjectSaved;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import librarievirtuala.Autor;
import librarievirtuala.Carte;
import librarievirtuala.Categorie;
import librarievirtuala.Editura;
import librarievirtuala.Rand;
import repositories.RanduriMemoryRepository;
import servicies.RanduriService;
import servicies.RanduriServiceImpl;

/**
 *
 * @author Andrei
 */
public class FrmAddEditRand extends javax.swing.JDialog {

    private List<Categorie> categori = new ArrayList<Categorie>();
    private DefaultComboBoxModel<Categorie> comboBoxModel;
    private List<Autor> autori = new ArrayList<Autor>();
    private List<Carte> carti = new ArrayList<Carte>();
    private List<Editura> edituri = new ArrayList<Editura>();
    private DefaultListModel<Carte> listModel;
    private OnBusinessObjectSaved businessObjectSaved;
    private Rand randSelectat;

    public FrmAddEditRand(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listModel = new DefaultListModel<>();
        edituri.add(new Editura("Patrate"));
        edituri.add(new Editura("Romburi"));
        edituri.add(new Editura("Cultura"));
        autori.add(new Autor("Gigel", 1995));
        autori.add(new Autor("Petru", 2000));
        autori.add(new Autor("Mircea", 1980));
        carti.add(new Carte("das", "La pere", "", 23.5));
        carti.add(new Carte("cev", "Cinci pasi", "", 15.99));
        carti.add(new Carte("cccc", "D&B", "", 12.5));
        carti.get(0).addAutor(autori.get(0));
        carti.get(0).setEditura(edituri.get(0));
        carti.get(1).addAutor(autori.get(1));
        carti.get(1).setEditura(edituri.get(1));
        carti.get(2).addAutor(autori.get(2));
        carti.get(2).setEditura(edituri.get(2));
        for (Carte carte : carti) {
            listModel.addElement(carte);
        }
        lstCarti.setModel(listModel);

    }

    public FrmAddEditRand(Rand randSelectat, JDialog parent, boolean modal) {
        this(parent, modal);
        this.randSelectat = randSelectat;
        txtNume.setText(randSelectat.getNume());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autorListRenderer1 = new renderers.AutorListRenderer();
        lblNume = new javax.swing.JLabel();
        lblCategorie = new javax.swing.JLabel();
        lblCarti = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCarti = new javax.swing.JList<>();
        btnSave = new javax.swing.JButton();
        lblRafturi = new javax.swing.JLabel();
        cmbRafturi = new javax.swing.JComboBox<>();
        cmbCategori = new javax.swing.JComboBox<>();

        autorListRenderer1.setText("autorListRenderer1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNume.setText("Nume:");

        lblCategorie.setText("Categorie:");

        lblCarti.setText("Lista Carti:");

        lstCarti.setCellRenderer(autorListRenderer1);
        jScrollPane1.setViewportView(lstCarti);

        btnSave.setText("Salvare");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblRafturi.setText("Raft:");

        cmbRafturi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNume, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCategorie, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRafturi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCarti, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNume, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(cmbRafturi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(cmbCategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNume)
                    .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategorie)
                    .addComponent(cmbCategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRafturi)
                    .addComponent(cmbRafturi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String denumireRand = txtNume.getText().trim();
        if (randSelectat == null) {
            Rand rand = new Rand();
            rand.setNume(denumireRand);
            for (Carte carte : lstCarti.getSelectedValuesList()) {
                rand.addCarte(carte);
            }
            businessObjectSaved.saveBusinessObject(rand);
            dispose();
        }
        randSelectat.setNume(denumireRand);
        for (Carte carte : lstCarti.getSelectedValuesList()) {

            randSelectat.addCarte(carte);
        }
        businessObjectSaved.saveBusinessObject(randSelectat);
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setBusinessObjectSaved(OnBusinessObjectSaved businessObjectSaved) {
        this.businessObjectSaved = businessObjectSaved;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private renderers.AutorListRenderer autorListRenderer1;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCategori;
    private javax.swing.JComboBox<String> cmbRafturi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarti;
    private javax.swing.JLabel lblCategorie;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblRafturi;
    private javax.swing.JList<Carte> lstCarti;
    private javax.swing.JTextField txtNume;
    // End of variables declaration//GEN-END:variables

}
