package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1



/**
 * AutoriCarti generated by hbm2java
 */
public class AutoriCarti  implements java.io.Serializable {


     private int id;
     private int idAutor;
     private int idCarte;

    public AutoriCarti() {
    }

    public AutoriCarti(int id, int idAutor, int idCarte) {
       this.id = id;
       this.idAutor = idAutor;
       this.idCarte = idCarte;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdAutor() {
        return this.idAutor;
    }
    
    public void setIdAutor(int idAutor) {
        this.idAutor = idAutor;
    }
    public int getIdCarte() {
        return this.idCarte;
    }
    
    public void setIdCarte(int idCarte) {
        this.idCarte = idCarte;
    }




}


