package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Autori generated by hbm2java
 */
public class Autori  implements java.io.Serializable {


     private int id;
     private String nume;
     private Date dataNasteri;

    public Autori() {
    }

	
    public Autori(int id) {
        this.id = id;
    }
    public Autori(int id, String nume, Date dataNasteri) {
       this.id = id;
       this.nume = nume;
       this.dataNasteri = dataNasteri;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public Date getDataNasteri() {
        return this.dataNasteri;
    }
    
    public void setDataNasteri(Date dataNasteri) {
        this.dataNasteri = dataNasteri;
    }




}


