package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1



/**
 * Carti generated by hbm2java
 */
public class Carti  implements java.io.Serializable {


     private int id;
     private int idEditura;
     private String isbn;
     private String nume;
     private String descriere;
     private Double pret;

    public Carti() {
    }

	
    public Carti(int id, int idEditura, String isbn, String nume) {
        this.id = id;
        this.idEditura = idEditura;
        this.isbn = isbn;
        this.nume = nume;
    }
    public Carti(int id, int idEditura, String isbn, String nume, String descriere, Double pret) {
       this.id = id;
       this.idEditura = idEditura;
       this.isbn = isbn;
       this.nume = nume;
       this.descriere = descriere;
       this.pret = pret;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdEditura() {
        return this.idEditura;
    }
    
    public void setIdEditura(int idEditura) {
        this.idEditura = idEditura;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getDescriere() {
        return this.descriere;
    }
    
    public void setDescriere(String descriere) {
        this.descriere = descriere;
    }
    public Double getPret() {
        return this.pret;
    }
    
    public void setPret(Double pret) {
        this.pret = pret;
    }




}


