package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1



/**
 * Persoane generated by hbm2java
 */
public class Persoane  implements java.io.Serializable {


     private int id;
     private String nume;
     private String cnp;

    public Persoane() {
    }

    public Persoane(int id, String nume, String cnp) {
       this.id = id;
       this.nume = nume;
       this.cnp = cnp;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getCnp() {
        return this.cnp;
    }
    
    public void setCnp(String cnp) {
        this.cnp = cnp;
    }




}


