package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersoaneAbonamente generated by hbm2java
 */
public class PersoaneAbonamente  implements java.io.Serializable {


     private int id;
     private int idPersoane;
     private int idAbonamente;
     private int idOperatori;
     private Date dataIncepere;
     private Date dataIncheiere;

    public PersoaneAbonamente() {
    }

    public PersoaneAbonamente(int id, int idPersoane, int idAbonamente, int idOperatori, Date dataIncepere, Date dataIncheiere) {
       this.id = id;
       this.idPersoane = idPersoane;
       this.idAbonamente = idAbonamente;
       this.idOperatori = idOperatori;
       this.dataIncepere = dataIncepere;
       this.dataIncheiere = dataIncheiere;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdPersoane() {
        return this.idPersoane;
    }
    
    public void setIdPersoane(int idPersoane) {
        this.idPersoane = idPersoane;
    }
    public int getIdAbonamente() {
        return this.idAbonamente;
    }
    
    public void setIdAbonamente(int idAbonamente) {
        this.idAbonamente = idAbonamente;
    }
    public int getIdOperatori() {
        return this.idOperatori;
    }
    
    public void setIdOperatori(int idOperatori) {
        this.idOperatori = idOperatori;
    }
    public Date getDataIncepere() {
        return this.dataIncepere;
    }
    
    public void setDataIncepere(Date dataIncepere) {
        this.dataIncepere = dataIncepere;
    }
    public Date getDataIncheiere() {
        return this.dataIncheiere;
    }
    
    public void setDataIncheiere(Date dataIncheiere) {
        this.dataIncheiere = dataIncheiere;
    }




}


