package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1



/**
 * Rafturi generated by hbm2java
 */
public class Rafturi  implements java.io.Serializable {


     private int id;
     private String nume;
     private int nrLinii;
     private int nrColoane;

    public Rafturi() {
    }

    public Rafturi(int id, String nume, int nrLinii, int nrColoane) {
       this.id = id;
       this.nume = nume;
       this.nrLinii = nrLinii;
       this.nrColoane = nrColoane;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public int getNrLinii() {
        return this.nrLinii;
    }
    
    public void setNrLinii(int nrLinii) {
        this.nrLinii = nrLinii;
    }
    public int getNrColoane() {
        return this.nrColoane;
    }
    
    public void setNrColoane(int nrColoane) {
        this.nrColoane = nrColoane;
    }




}


