package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1



/**
 * Randuri generated by hbm2java
 */
public class Randuri  implements java.io.Serializable {


     private int id;
     private String nume;
     private int idRafturi;

    public Randuri() {
    }

    public Randuri(int id, String nume, int idRafturi) {
       this.id = id;
       this.nume = nume;
       this.idRafturi = idRafturi;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public int getIdRafturi() {
        return this.idRafturi;
    }
    
    public void setIdRafturi(int idRafturi) {
        this.idRafturi = idRafturi;
    }




}


