package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1



/**
 * Tipuri generated by hbm2java
 */
public class Tipuri  implements java.io.Serializable {


     private int id;
     private String nume;

    public Tipuri() {
    }

    public Tipuri(int id, String nume) {
       this.id = id;
       this.nume = nume;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }




}


