package dbmodels;
// Generated 21-Sep-2021 18:46:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TipuriPersoane generated by hbm2java
 */
public class TipuriPersoane  implements java.io.Serializable {


     private int id;
     private int idPersoane;
     private int idTipuri;
     private Date dateStart;
     private Date dateEnd;

    public TipuriPersoane() {
    }

    public TipuriPersoane(int id, int idPersoane, int idTipuri, Date dateStart, Date dateEnd) {
       this.id = id;
       this.idPersoane = idPersoane;
       this.idTipuri = idTipuri;
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdPersoane() {
        return this.idPersoane;
    }
    
    public void setIdPersoane(int idPersoane) {
        this.idPersoane = idPersoane;
    }
    public int getIdTipuri() {
        return this.idTipuri;
    }
    
    public void setIdTipuri(int idTipuri) {
        this.idTipuri = idTipuri;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }




}


